Validacoes
Renato-Miranda/socialMedia-API pull request #8
Opened 2023-09-19 23:21 UTC by Renato-Miranda

validações de nomeUsuario;
email;
senha;
conteudo de posts e comentários.

2023-09-19 23:59 UTC, Joa1zin requested changes
src/model/CurtidoModel.js
linha 2 - corrigir o 'pots' para 'post'
linha 4 - corrigir o 'pots' para 'post'

2023-09-20 00:10 UTC, Joa1zin approved these changes
ok 👍🏾 🥇

2023-09-20 00:10 UTC, merged

2023-09-20 00:16 UTC, Renato-Miranda commented
thanks 🤝🏽

2023-09-20 12:19 UTC, Joa1zin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Criar Validações](https://trello.com/c/1rDsnlm3/20-criar-valida%C3%A7%C3%B5es)